apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nginx
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 20
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress
spec:
  defaultBackend:
    service:
      name: cute-service
      port:
        number: 80
---
apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: be-cf
spec:
  securityPolicy:
    name: "cute-policy"
---
apiVersion: v1
kind: Service
metadata:
  name: cute-service
  annotations:
    cloud.google.com/backend-config: '{"default": "be-cf"}'
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
