apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: "/usr/share/nginx/"
              name: pvc-claim
      volumes:
        - name: pvc-claim
---
apiVersion: v1
kind: Service
metadata:
  name: cutelb
  annotations:
    cloud.google.com/l4-rbs: "enabled"
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  selector:
    app: nginx
  ports:
    - name: tcp-port
      port: 8080
      targetPort: 80
