swagger: "2.0"
info:
  title: coolkie-api
  description: store-api
  version: 1.0.0
paths:
  /products:
    get:
      summary: get products list
      operationId: uwuproduct
      x-google-backend:
        address: { backend-url }
      responses:
        "200":
          description: sucuwussful
          schema:
            type: string
  /buy:
    get:
      summary: get bought products list
      operationId: uwubought
      x-google-backend:
        address: { backend-url }
      responses:
        "200":
          description: sucuwussful
          schema:
            type: string
  /aisearch:
    get:
      summary: aisearch
      operationId: uwusearch
      x-google-backend:
        address: { backend-url }
      responses:
        "200":
          description: sucuwussful
          schema:
            type: string
